<a href="https://colab.research.google.com/github/ralsouza/machine_learning_python/blob/master/notebooks/03_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predictive classification model to predict the binary variable value (true or false) from numeric data.

In [1]:
# Import modules
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")

In [3]:
# Train data
n_train = 10
np.random.seed(0)
df_train = pd.DataFrame({"var1": np.random.random(n_train), \
                         "var2": np.random.random(n_train), \
                         "var3": np.random.random(n_train), \
                         "var4": np.random.randint(0,2,n_train).astype(bool),\
                         "target": np.random.randint(0,2,n_train).astype(bool)})

In [23]:
df_train.shape

(10, 5)

In [24]:
df_train.head()

var1      var2      var3   var4  target
0  0.548814  0.791725  0.978618   True    True
1  0.715189  0.528895  0.799159  False    True
2  0.602763  0.568045  0.461479   True   False
3  0.544883  0.925597  0.780529  False   False
4  0.423655  0.071036  0.118274   True   False

In [5]:
# Test data
n_test = 3
np.random.seed(1)
df_test = pd.DataFrame({"var1": np.random.random(n_test), \
                        "var2": np.random.random(n_test), \
                        "var3": np.random.random(n_test), \
                        "var4": np.random.randint(0,2,n_test).astype(bool),\
                        "target": np.random.randint(0,2,n_test).astype(bool)})


In [25]:
df_test.shape

(3, 5)

In [6]:
df_test.head()

var1      var2      var3   var4  target
0  0.417022  0.302333  0.186260  False    True
1  0.720324  0.146756  0.345561  False   False
2  0.000114  0.092339  0.396767  False   False

# Crie um modelo com PCA para redução de dimensionalidade com 3 componentes

In [9]:
pca = PCA(n_components = 3)

# Aplique o PCA aos datasets

In [28]:
# Reduce train
reduced_train = pca.fit_transform(df_train)

# Reduce test
reduced_test = pca.fit_transform(df_test)

test reduced dataset [[ 6.89139038e-01 -3.17845183e-02  2.61682076e-17]
 [-2.98826575e-01  3.75028835e-01  2.61682076e-17]
 [-3.90312463e-01 -3.43244317e-01  2.61682076e-17]]


# Crie dataframes do pandas com o resultado do item anterior

array([[-0.05031997,  0.36749102,  0.89139179],
       [-0.60506978, -0.09097852,  0.13264423],
       [ 0.7908364 ,  0.29795093,  0.16538337],
       [ 0.30589171, -0.64224325, -0.06037678],
       [ 0.77490575,  0.72379607, -0.29189175],
       [-0.64367659,  0.22377466, -0.17565896],
       [-0.58205781,  0.46270265, -0.52416353],
       [ 0.23453532, -0.70169405,  0.04923808],
       [-0.57645959, -0.17945647,  0.13489648],
       [ 0.35141457, -0.46134304, -0.32146293]])

# Crie um modelo de regressão logística

# Usando o recurso de pipeline do scikit-learn para encadear 2 algoritmos em um mesmo modelo, concatene o resultado do PCA e Regressão Logística


# Faça previsões com o modelo treinado

# Imprimindo as previsões